#include <mosqueeze/DecisionMatrix.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string_view>

// Compile-time embedded JSON (generated by cmake/EmbedData.cmake)
#if __has_include("decision_matrix_data.hpp")
#include "decision_matrix_data.hpp"
#define MOSQUEEZE_HAS_EMBEDDED_DATA 1
#endif

namespace mosqueeze {

// ---------------------------------------------------------------------------
// Static helpers
// ---------------------------------------------------------------------------

static FileType classifyExtension(const std::string& ext) {
    static const std::unordered_map<std::string, FileType> kMap = {
        {".json",   FileType::Text_Structured},
        {".xml",    FileType::Text_Structured},
        {".yaml",   FileType::Text_Structured},
        {".yml",    FileType::Text_Structured},
        {".csv",    FileType::Text_Structured},
        {".html",   FileType::Text_Prose},
        {".htm",    FileType::Text_Prose},
        {".css",    FileType::Text_Prose},
        {".txt",    FileType::Text_Prose},
        {".md",     FileType::Text_Prose},
        {".rst",    FileType::Text_Prose},
        {".cpp",    FileType::Text_SourceCode},
        {".c",      FileType::Text_SourceCode},
        {".h",      FileType::Text_SourceCode},
        {".hpp",    FileType::Text_SourceCode},
        {".py",     FileType::Text_SourceCode},
        {".js",     FileType::Text_SourceCode},
        {".ts",     FileType::Text_SourceCode},
        {".java",   FileType::Text_SourceCode},
        {".go",     FileType::Text_SourceCode},
        {".rs",     FileType::Text_SourceCode},
        {".log",    FileType::Text_Log},
        {".jpg",    FileType::Image_JPEG},
        {".jpeg",   FileType::Image_JPEG},
        {".png",    FileType::Image_PNG},
        {".webp",   FileType::Image_WebP},
        {".heic",   FileType::Image_WebP},
        {".heif",   FileType::Image_WebP},
        {".avif",   FileType::Image_WebP},
        {".arw",    FileType::Image_Raw},
        {".cr2",    FileType::Image_Raw},
        {".nef",    FileType::Image_Raw},
        {".raf",    FileType::Image_Raw},
        {".dng",    FileType::Image_Raw},
        {".mp4",    FileType::Video_MP4},
        {".mov",    FileType::Video_MP4},
        {".mkv",    FileType::Video_MKV},
        {".webm",   FileType::Video_WebM},
        {".avi",    FileType::Video_AVI},
        {".wav",    FileType::Audio_WAV},
        {".mp3",    FileType::Audio_MP3},
        {".flac",   FileType::Audio_FLAC},
        {".aac",    FileType::Audio_MP3},
        {".7z",     FileType::Archive_7Z},
        {".zip",    FileType::Archive_ZIP},
        {".gz",     FileType::Archive_TAR},
        {".z",      FileType::Archive_TAR},
        {".tar",    FileType::Archive_TAR},
        {".docx",   FileType::Archive_ZIP},
        {".pptx",   FileType::Archive_ZIP},
        {".xlsx",   FileType::Archive_ZIP},
        {".db",     FileType::Binary_Database},
        {".sqlite", FileType::Binary_Database},
        {".sqlite3",FileType::Binary_Database},
        {".pdf",    FileType::Document_PDF},
    };
    auto it = kMap.find(ext);
    return it != kMap.end() ? it->second : FileType::Unknown;
}

// Parse "algo/level" → {"algo", level}.  Normalises "xz" → "lzma".
static std::pair<std::string, int> parseAlgoLevel(const std::string& s) {
    const auto slash = s.find('/');
    if (slash == std::string::npos) return {s, 0};
    std::string algo = s.substr(0, slash);
    if (algo == "xz") algo = "lzma";
    int level = 0;
    try { level = std::stoi(s.substr(slash + 1)); } catch (...) {}
    return {algo, level};
}

struct ParsedEntry {
    std::string algorithm;
    int level = 0;
    double ratio = 1.0;
    long long timeMs = 0;
};

// Parse "algo/level (R.RRx in Tms)" → ParsedEntry or nullopt.
static std::optional<ParsedEntry> parseOptEntry(const std::string& s) {
    static const std::regex kPat(R"(^([^/]+)/(\d+)\s+\(([0-9.]+)x\s+in\s+(\d+)ms\)$)");
    std::smatch m;
    if (!std::regex_match(s, m, kPat)) return std::nullopt;
    ParsedEntry e;
    e.algorithm = m[1].str();
    if (e.algorithm == "xz") e.algorithm = "lzma";
    try {
        e.level  = std::stoi(m[2].str());
        e.ratio  = std::stod(m[3].str());
        e.timeMs = std::stoll(m[4].str());
    } catch (...) { return std::nullopt; }
    return e;
}

// ---------------------------------------------------------------------------
// Prediction helpers
// ---------------------------------------------------------------------------

const PredictionOption* Prediction::getBest() const {
    return options.empty() ? nullptr : &options[0];
}

const PredictionOption* Prediction::getFastest() const {
    if (options.size() > 1) return &options[1];
    return options.empty() ? nullptr : &options[0];
}

const PredictionOption* Prediction::getBalanced() const {
    if (options.size() > 2) return &options[2];
    if (options.size() > 1) return &options[1];
    return options.empty() ? nullptr : &options[0];
}

// ---------------------------------------------------------------------------
// DecisionMatrix
// ---------------------------------------------------------------------------

DecisionMatrix::DecisionMatrix() = default;

bool DecisionMatrix::loadDefault() {
#ifdef MOSQUEEZE_HAS_EMBEDDED_DATA
    return parseJsonContent(resources::kDecisionMatrixJson);
#else
    return false;
#endif
}

bool DecisionMatrix::loadFromFile(const std::filesystem::path& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;
    std::ostringstream ss;
    ss << f.rdbuf();
    return parseJsonContent(ss.str());
}

bool DecisionMatrix::parseJsonContent(std::string_view content) {
    try {
        const auto j = nlohmann::json::parse(content);

        if (j.contains("generated"))
            generatedDate_ = j["generated"].get<std::string>();

        if (!j.contains("decision_matrix")) return false;

        data_.clear();
        totalBenchmarks_ = 0;

        for (auto& [ext, entry] : j["decision_matrix"].items()) {
            ExtensionData ed;
            ed.fileCount = entry.value("file_count", size_t{0});
            ed.testCount = entry.value("test_count", size_t{0});
            ed.avgRatio  = entry.value("avg_ratio",  1.0);
            ed.bestRatio = entry.value("best_ratio", 1.0);

            const std::string ratioAlgoStr = entry.value("best_ratio_algo", "zstd/22");
            auto [algo, lvl] = parseAlgoLevel(ratioAlgoStr);
            ed.bestRatioAlgo  = algo;
            ed.bestRatioLevel = lvl;

            bool hasFast = false, hasBalanced = false;

            if (entry.contains("best_fast") && !entry["best_fast"].is_null()) {
                if (auto p = parseOptEntry(entry["best_fast"].get<std::string>())) {
                    ed.bestFastAlgo  = p->algorithm;
                    ed.bestFastLevel = p->level;
                    ed.bestFastRatio = p->ratio;
                    hasFast = true;
                }
            }

            if (entry.contains("best_balanced") && !entry["best_balanced"].is_null()) {
                if (auto p = parseOptEntry(entry["best_balanced"].get<std::string>())) {
                    ed.bestBalancedAlgo  = p->algorithm;
                    ed.bestBalancedLevel = p->level;
                    ed.bestBalancedRatio = p->ratio;
                    hasBalanced = true;
                }
            }

            // Skip extensions where compression provides minimal benefit and
            // no fast or balanced option exists.
            if (ed.avgRatio < 1.1 && !hasFast && !hasBalanced) {
                ed.skip = true;
                std::ostringstream reason;
                reason << "Already-compressed or incompressible format " << ext
                       << " (avg. ratio " << std::fixed
                       << std::setprecision(3) << ed.avgRatio << "x)";
                ed.skipReason = reason.str();
            }

            totalBenchmarks_ += ed.testCount;
            data_.emplace(ext, std::move(ed));
        }

        // Override skip for known already-compressed formats where benchmark
        // data may show misleading ratios (e.g. FLAC/PDF with embedded
        // compressed streams) but secondary compression provides minimal gain.
        applySkipOverrides();

        return true;
    } catch (const std::exception&) {
        return false;
    }
}

void DecisionMatrix::applySkipOverrides() {
    static const std::unordered_map<std::string, std::string> kSkipOverrides = {
        {".flac", "Already FLAC compressed, secondary compression < 10% gain"},
        {".pdf",  "PDF internal compression often sufficient, < 5% gain"},
    };

    for (const auto& [ext, reason] : kSkipOverrides) {
        auto it = data_.find(ext);
        if (it != data_.end()) {
            it->second.skip = true;
            it->second.skipReason = reason;
            it->second.results.clear();
        }
    }
}

CompressionSpeed DecisionMatrix::classifySpeed(std::chrono::milliseconds t) const {
    if (t.count() < 100)  return CompressionSpeed::Fast;
    if (t.count() < 1000) return CompressionSpeed::Medium;
    return CompressionSpeed::Slow;
}

static std::string speedLabel(CompressionSpeed s) {
    switch (s) {
        case CompressionSpeed::Fast:   return "fast";
        case CompressionSpeed::Medium: return "medium";
        case CompressionSpeed::Slow:   return "slow";
    }
    return "slow";
}

std::string DecisionMatrix::fileExtensionToLower(const std::filesystem::path& path) const {
    std::string ext = path.extension().string();
    std::transform(ext.begin(), ext.end(), ext.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return ext;
}

Prediction DecisionMatrix::buildFallback(const std::string& ext, size_t fileSize) {
    Prediction p;
    p.fileExtension = ext;
    p.fileType      = classifyExtension(ext);
    p.shouldSkip    = false;

    PredictionOption opt;
    opt.algorithm     = "zstd";
    opt.level         = 22;
    opt.estimatedRatio = 1.0;
    opt.estimatedSize  = fileSize;          // no ratio info → size unchanged
    opt.speed          = CompressionSpeed::Medium;
    opt.speedLabel     = "medium";
    opt.fallbackAlgorithm = "lzma";
    opt.fallbackLevel     = 9;
    opt.fallbackRatio     = 1.0;
    p.options.push_back(std::move(opt));
    return p;
}

Prediction DecisionMatrix::buildPrediction(
    const std::string& ext,
    const ExtensionData& ed,
    size_t fileSize) const
{
    Prediction p;
    p.fileExtension = ext;
    p.fileType      = classifyExtension(ext);

    if (ed.skip) {
        p.shouldSkip = true;
        p.skipReason = ed.skipReason;
        return p;
    }

    auto makeOpt = [&](const std::string& algo, int level, double ratio,
                       std::chrono::milliseconds encTime) -> PredictionOption {
        PredictionOption opt;
        opt.algorithm      = algo;
        opt.level          = level;
        opt.estimatedRatio = ratio;
        opt.estimatedSize  = (fileSize > 0 && ratio > 0.0)
                             ? static_cast<size_t>(fileSize / ratio)
                             : 0;
        opt.speed          = classifySpeed(encTime);
        opt.speedLabel     = mosqueeze::speedLabel(opt.speed);
        return opt;
    };

    // Option 0 — best ratio (typically slow; we have no encode time, assume slow)
    auto best = makeOpt(ed.bestRatioAlgo, ed.bestRatioLevel, ed.bestRatio,
                        std::chrono::milliseconds{2000});

    // Option 1 — fastest (< 100ms)
    std::optional<PredictionOption> fast;
    if (!ed.bestFastAlgo.empty()) {
        // best_fast time is embedded in the string; we classified during parse.
        // Re-derive from ratio label: fast entries were selected at < 100ms.
        fast = makeOpt(ed.bestFastAlgo, ed.bestFastLevel, ed.bestFastRatio,
                       std::chrono::milliseconds{50});
    }

    // Option 2 — balanced
    std::optional<PredictionOption> balanced;
    if (!ed.bestBalancedAlgo.empty()) {
        balanced = makeOpt(ed.bestBalancedAlgo, ed.bestBalancedLevel,
                           ed.bestBalancedRatio, std::chrono::milliseconds{300});
    }

    // Wire fallbacks between options
    if (fast) {
        best.fallbackAlgorithm = fast->algorithm;
        best.fallbackLevel     = fast->level;
        best.fallbackRatio     = fast->estimatedRatio;
    } else if (balanced) {
        best.fallbackAlgorithm = balanced->algorithm;
        best.fallbackLevel     = balanced->level;
        best.fallbackRatio     = balanced->estimatedRatio;
    } else {
        best.fallbackAlgorithm = "zstd";
        best.fallbackLevel     = 3;
        best.fallbackRatio     = ed.avgRatio;
    }

    p.options.push_back(std::move(best));

    if (fast) {
        if (balanced) {
            fast->fallbackAlgorithm = balanced->algorithm;
            fast->fallbackLevel     = balanced->level;
            fast->fallbackRatio     = balanced->estimatedRatio;
        } else {
            fast->fallbackAlgorithm = "zstd";
            fast->fallbackLevel     = 3;
            fast->fallbackRatio     = ed.avgRatio;
        }
        p.options.push_back(std::move(*fast));
    }

    if (balanced) {
        balanced->fallbackAlgorithm = "zstd";
        balanced->fallbackLevel     = 3;
        balanced->fallbackRatio     = ed.avgRatio;
        p.options.push_back(std::move(*balanced));
    }

    return p;
}

Prediction DecisionMatrix::predict(const std::string& extension, size_t fileSize) const {
    // Normalise to lowercase with leading dot
    std::string ext = extension;
    if (!ext.empty() && ext[0] != '.') ext = '.' + ext;
    std::transform(ext.begin(), ext.end(), ext.begin(),
                   [](unsigned char c) { return std::tolower(c); });

    auto it = data_.find(ext);
    if (it == data_.end()) return buildFallback(ext, fileSize);
    return buildPrediction(ext, it->second, fileSize);
}

Prediction DecisionMatrix::predict(const std::filesystem::path& file) const {
    std::error_code ec;
    size_t fileSize = 0;
    if (std::filesystem::exists(file, ec) && !ec) {
        auto sz = std::filesystem::file_size(file, ec);
        if (!ec) fileSize = sz;
    }
    return predict(fileExtensionToLower(file), fileSize);
}

bool DecisionMatrix::hasData(const std::string& extension) const {
    std::string ext = extension;
    if (!ext.empty() && ext[0] != '.') ext = '.' + ext;
    std::transform(ext.begin(), ext.end(), ext.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return data_.count(ext) > 0;
}

std::vector<std::string> DecisionMatrix::knownExtensions() const {
    std::vector<std::string> result;
    result.reserve(data_.size());
    for (const auto& [ext, _] : data_) result.push_back(ext);
    std::sort(result.begin(), result.end());
    return result;
}

size_t DecisionMatrix::totalEntries() const {
    return data_.size();
}

size_t DecisionMatrix::totalBenchmarks() const {
    return totalBenchmarks_;
}

} // namespace mosqueeze
